services:
  - name: cri-containerd
    image: linuxkit/cri-containerd:f216f883c63b26b48f08af83696d211e7413cca5
    cgroupsPath: podruntime/cri-containerd
files:
  - path: /etc/kubelet.sh.conf
    contents: |
      KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-containerd.sock"
