services:
  - name: kubernetes-docker-image-cache-control-plane
    image: linuxkit/kubernetes-docker-image-cache-control-plane:139f1a654743704a4878e3406390538008560be6-dirty
    cgroupsPath: podruntime/control-cache
