kernel:
  image: linuxkit/kernel:4.19.56
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:v0.7
  - linuxkit/runc:v0.7
  - linuxkit/containerd:v0.7
  - linuxkit/ca-certificates:v0.7
onboot:
  - name: modprobe
    image: linuxkit/modprobe:v0.7
    command: ["modprobe", "rbd"]
  - name: sysctl
    image: linuxkit/sysctl:v0.7
    binds:
     - /etc/sysctl.d/01-kubernetes.conf:/etc/sysctl.d/01-kubernetes.conf
    readonly: false
  - name: sysfs
    image: linuxkit/sysfs:v0.7
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.7
  - name: format
    image: linuxkit/format:v0.7
  - name: mounts
    image: linuxkit/mount:v0.7
    command: ["/usr/bin/mountie", "/var/lib/"]
services:
  - name: rngd
    image: linuxkit/rngd:v0.7
    cgroupsPath: systemreserved/rngd
  - name: eudev
    image: linuxkit/eudev:1ca7f912b8d037a5a0bccb2c54c77eaa7fd36f8a
    cgroupsPath: systemreserved/eudev
  - name: ntpd
    image: linuxkit/openntpd:v0.7
    cgroupsPath: systemreserved/ntpd
  - name: sshd
    image: linuxkit/sshd:v0.7
    cgroupsPath: systemreserved/sshd
  - name: kubelet
    image: linuxkit/kubelet:4c3974d5ffa7de9769e5142056d453dc562481b7-dirty
    cgroupsPath: podruntime/kubelet
  - name: getty
    image: linuxkit/getty:v0.7
    env:
     - INSECURE=true
    cgroupsPath: systemreserved/getty
files:
  - path: etc/linuxkit.yml
    metadata: yaml
  - path: /etc/kubernetes
    symlink: "/var/lib/kubeadm"
  - path: /etc/os-release
    contents: |
      PRETTY_NAME="LinuxKit Kubernetes Project"
  - path: /usr/libexec/kubernetes/kubelet-plugins
    symlink: "/var/lib/kubelet-plugins"
  - path: /etc/kubeadm/
    directory: true
  - path: /etc/sysctl.d/01-kubernetes.conf
    contents: |+
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
  - path: /etc/cni/net.d
    directory: true
  - path: /opt/cni/bin
    directory: true
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
    - library
